### ISSUE TITLE
Mouse input not working

### ISSUE THREAD

**Issue by ischorr** [agmsmith/VNC-4.0-BeOS-Server#2]
Mouse input doesn't seem to be working for me.  input_server is running and keyboard input works.  If ShowCheapCursor is enabled I do see the local mouse cursor change.

Have tried several different VNC clients including Remmina and a couple RealVNC clients I had on hand.  I've tried various combinations of what few options I've found to try (including disabling screen capture methods, disabling local cursor on client, disabling shared modes, etc) but no change.  I don't see any evidence that cursor position updates or click events are being processed.

In debug logging or syslog I don't see anything related to mouse or input being logged.

vncserver:  v1.34
Haiku R1Beta2 (Feb 2021)

**Comment by agmsmith** [comment]
See if the InputEventInjector has been installed to the right place.  Just do a desktop search (alt-f) for Injector and you should see something like this in recent Haiku OS installs:

![EventInjectorScreenShot](https://user-images.githubusercontent.com/5384795/123513138-6af7f300-d659-11eb-9248-f66d62999438.png)

**Comment by ischorr** [comment]
Looks like it was triggered by the VMW addons.  With "Mouse sharing enabled" set, will see this problem.  Not sure if this is something that could/should work still, but that's the trigger in my case at least.

**Comment by agmsmith** [comment]
So, this is a VM guest add-on to Haiku that lets their mouse get in?  Probably ignores other mouse input events and throws them away rather than passing them through.

**Comment by ischorr** [comment]
Yes-ish.  VM guest add-on (https://github.com/HaikuArchives/VMwareAddons).  It synchronizes the position of the remote cursor with the local cursor, which helps with speed of updates and weirdness caused by differences in mouse acceleration behaviors and things between the guest OS and the controlling OS.  And makes it easier to support having the mouse transparently enter/leave the VM window when the guest OS is being displayed in, well, a window.  

I believe it shifts to use absolute cursor positioning, though not sure what specifically is breaking things for vncserver.

**Comment by agmsmith** [comment]
Probably sending the absolute mouse position every frame, so if VNC moves the mouse, VMWare moves it back to the absolute position soon after.  If that's the bug, change their code to only create a mouse event if their mouse coordinates are different.

**Comment by ischorr** [comment]
Maybe.  You'd think you'd see some "jitter" in the cursor behavior unless the filter ends up intercepting and changing the position back before anything is actually written to the screen.  It does seem to capture B_MOUSE_MOVED events and potentially modify them.

But in this case it's not just position - even mouse clicks from VNC aren't making it all the way through (I just don't know where they're being eaten).

**Comment by agmsmith** [comment]
Hmmm.  I'm using VirtualBox over here, and with it running in fake USB tablet mode (absolute position, integrates nicely with the host mouse pointer - can move it out of the VM without having to hit a key), VNC works fine.  Moving the VNC mouse or the host mouse works seamlessly.  Doesn't even have a guest add-on installed.

**Comment by heyvito** [comment]
> Looks like it was triggered by the VMW addons. With "Mouse sharing enabled" set, will see this problem. Not sure if this is something that could/should work still, but that's the trigger in my case at least.

And that was it! I'm so happy I found this message. Disabling VMW mouse sharing (right from the tray) did the trick!

**Comment by agmsmith** [comment]
Nice to hear that you found out how to make it work!
